language: objective-c
osx_image: xcode7.1
script:
  - xcodebuild -project StomtiOS.xcodeproj -scheme StomtiOS -sdk iphonesimulator9.1 -sdk iphonesimulator10.0.3 -destination 'platform=iOS Simulator,name=iPhone 6' ONLY_ACTIVE_ARCH=NO build test
